[project]
name = "code-gym-ai-investment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "openai>=2.15.0",
    "plotly>=6.5.1",
    "streamlit>=1.52.2",
]
